### ISSUE TITLE
Feature 2: List Subscription Plans

### ISSUE THREAD

**Issue by csys-fresher-batch-2021** [csys-fresher-batch-2021/subscriptionapp-core-sakthi#3]
#### User Story
* As a user, I want to view the subscription plans for the selected channel.

Table:  channel_plans
Columns:  id, channel_id, plan_name, price, validity 

* plan_name : MONTHLY, YEARLY
* validity: 30 days or 365 days

e.g: Hotstar

* Monthly : 100
* Yearly: 1000

**Comment by sakthi14priya** [comment]
I will display the subscription plan
